### ISSUE TITLE
Catch if a translation is not provided in the selected language

### ISSUE THREAD

**Issue by enyineer** [the-moebius/fluent#2]
Hi,

first of all, thank you for this great package! Is there any possibility to catch whenever a translation that has been used was not found in any of the added translation files? It would be nice to be able to send such events eg. to Sentry to fix it asap. Otherwise you don't know when that happens.

I'd suggest the possibility to set an error handler that gets called whenever this happens. This could also include the situation when a variable is used in a translation that has not been provided in the translation context.

Thanks in advance!

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this library!

Actually, there are already warning messages that are getting logged to the console, e.g.:

```
Translation message (welcome) is not found for locale(s): en-GB
Translation (welcome) was not found for requested locale(s): en
```

See this [example](https://github.com/the-moebius/fluent/blob/main/examples/not-found.ts).

So it should be possible to catch by the tools like Sentry.

Also, from the README:

> If all matched translations doesn't have the specified message, then the generic placeholder will be returned instead (e.g. {message-id}). The library will also generate warning messages in the console to let you know when any specific translation doesn't have the specified message (so you can fix it).

---

However, the feature request makes sense, I'll look into it 👌🏻

**Comment by enyineer** [comment]
Allright, gotcha! Thank you. However, when deploying an application via eg. Firebase, "console.log" etc. doesn't work. Is there any way to provide a logger interface that is then used for such logging messages? Otherwise things might get lost (sometimes that even happens in prod, whoopsie...). This would also enable us to send such warnings to Sentry.
Nonetheless, thanks for this amazing package 🎉

I could try and create a PR as soon as I find time.

**Comment by slavafomin** [comment]
> However, when deploying an application via eg. Firebase, "console.log" etc. doesn't work.

`console.log` is a very basic tool in Node.js to work with process'es stdout stream. If some tool doesn't support such logging, it'a a drawback of the tool. However, I see that Firebase [actually supports this](https://firebase.google.com/docs/functions/writing-and-viewing-logs#console-log).

But I gotcha, the fix is on the way already.

**Comment by enyineer** [comment]
Oh. My bad. I didnt know about that, just that it didn't work. If it's not too much of a hastle for you, this would still be appreciated for integration into logging frameworks. Thank you a lot ❤️

**Comment by slavafomin** [comment]
@enyineer please try [the new feature](https://github.com/the-moebius/fluent/tree/warning-handling#warning-handling) (`npm i @moebius/fluent@next`).

Let me know if everything good, so I will publish it as a new minor version later.

**Comment by enyineer** [comment]
LGTM!

```typescript
export class FluentWarningHandler implements WarningHandler {
  handleWarning(warning: Warning): void {
    if (warning.type === "translate.missing-translation") {
      const err = new Error(`Caught missing translation (locales: ${warning.locales}): ${warning.path}`);
      Sentry.captureException(err);
    }
  }
}
```

```typescript
const fluent = new Fluent({
  warningHandler: new FluentWarningHandler(),
});
```

![grafik](https://user-images.githubusercontent.com/27201677/159132976-0f227e96-668e-4b08-8ea3-44736ce13532.png)

![grafik](https://user-images.githubusercontent.com/27201677/159132997-0064bfbe-f1f6-4f96-bce3-2d7d8e824a7a.png)

Thanks a lot!

**Comment by slavafomin** [comment]
> @moebius/fluent 1.1.0 published
